version: "3.0"

services:
  predix-edge-broker:
    image: "dtr.predix.io/predix-edge/predix-edge-broker:amd64-latest"
    hostname: 127.0.0.1
    ports:
      - 1883:1883

  opcua:
    image: "dtr.predix.io/predix-edge/protocol-adapter-opcua:amd64-latest"
    environment:
      config: "/config/config-opcua.json"
    volumes:
      - ./config:/config
      - ./data:/data


  cloud_gateway:
    image: "dtr.predix.io/predix-edge/cloud-gateway:amd64-latest"
    environment:
      config: "/config/config-cloud-gateway.json"
      https_proxy: "http://proxy-src.research.ge.com:8080"

    volumes:
      - ./config:/config
      - ./data:/data
      - ./data:/edge-agent
