version: "3.0"

services:
  opcua:
    image: "dtr.predix.io/predix-edge/protocol-adapter-opcua-amd64:latest"
    environment:
      config: "/config/config-opcua.json"
    networks:
      - predix-edge-broker_net

  edge-app:
    image: "my-edge-app:1.0.0"
    networks:
      - predix-edge-broker_net

  cloud_gateway:
    image: "dtr.predix.io/predix-edge/cloud-gateway-amd64:latest"
    environment:
      config: "/config/config-cloud-gateway.json"
    env_file:
      - /etc/environment
    networks:
      - predix-edge-broker_net

networks:
  predix-edge-broker_net:
    external: true
