version: "3.0"

services:
  opcua:
    image: "dtr.predix.io/predix-edge/protocol-adapter-opcua-amd64:1.0.8"
    environment:
      config: "/config/config-opcua.json"
    networks:
      - predix-edge-broker_net
  cloud_gateway_timeseries:
    image: "dtr.predix.io/predix-edge/cloud-gateway-timeseries-amd64:latest"
    environment:
      config: "/config/config-cloud-gateway.json"
    env_file:
      - /etc/environment
    networks:
      - predix-edge-broker_net
networks:
  predix-edge-broker_net:
    external: true
